### ISSUE TITLE
When deploying on Ubuntu, extra rtl-sdr settings required

### ISSUE THREAD

**Issue by adammatthews** [tbouron/MMM-FlightTracker#3]
Hi,

Thanks for this extension, its really awesome! I have configured MagicMirror in **serveronly** mode for testing and I'll likely leave it on a server and deploy RPi's where needed. 

I deployed on Ubuntu 19.04, and it got stuck at "Connecting Tracker".  I had to install build-essential to get 'make', I then needed the do the librtlstr step, and then the npm install step as per https://github.com/watson/rtl-sdr. 

	• sudo apt-get install build-essential
	• apt-get install librtlsdr-dev
	• npm install rtl-sdr --save

After that, all working fantastic! I'm using a PiAware Install on another Pi, with Network mode hooking into 30003.  Thanks again! 
![image](https://user-images.githubusercontent.com/2661060/73594261-ae9e0a00-4504-11ea-9d07-dc0f575bdfd2.png)

**Comment by tbouron** [comment]
Thanks @adammatthews, glad you made it work. Indeed, you need to install first `librtlsdr-dev` (which should also install the necessary dependencies) as per as [the prerequisite section of README.md](https://github.com/tbouron/MMM-FlightTracker#prerequisites).

Maybe it wasn't clear enough?

**Comment by adammatthews** [comment]
Yeah I did do that, maybe I wasn’t clear enough!

As an additional step on Ubuntu, when deploying a MM serveronly setup, I had to run build-essential to get ‘make’, and run npm install rtl-sdr to get it all to work, on top of just running install librtlsdr-dev. Just for reference in case anyone else is deploying on Ubuntu!

**Comment by adammatthews** [comment]
Closing issue, update the docs if desired or just have this for reference!
