### ISSUE TITLE
unable to get it to work

### ISSUE THREAD

**Issue by psycho2288** [tbouron/MMM-FlightTracker#4]
Trying to connect via the Network.  But all I see on the MM module is "Connecting to tracker"

I've included a screenshot of my config
![2020-06-30 17_22_59-Window](https://user-images.githubusercontent.com/67572284/86182989-a61f1f00-baf6-11ea-8426-79503df6b766.png)

**Comment by brynnflynn** [comment]
You need to update the host to the IP of your device. acme.com is just a placeholder.
